/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

/**
 *
 * @author hasaan
 */
public class AboutJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelpJFrame
     */
    public AboutJFrame() {
        initComponents();
        HelpfulStaticFunctions.locateAtCentre(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlejLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataSourcejTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        devTeamjTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");
        setAlwaysOnTop(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        titlejLabel.setBackground(new java.awt.Color(204, 204, 204));
        titlejLabel.setFont(new java.awt.Font("Luminari", 0, 36)); // NOI18N
        titlejLabel.setForeground(new java.awt.Color(204, 0, 0));
        titlejLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlejLabel.setText("Crossword Puzzle Creator");
        titlejLabel.setToolTipText("");
        titlejLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titlejLabelMouseClicked(evt);
            }
        });
        titlejLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titlejLabelKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dataSourcejTextArea.setEditable(false);
        dataSourcejTextArea.setBackground(new java.awt.Color(238, 238, 238));
        dataSourcejTextArea.setColumns(20);
        dataSourcejTextArea.setLineWrap(true);
        dataSourcejTextArea.setRows(5);
        dataSourcejTextArea.setText("It should be a \".txt\" file containing {CLUE}${ANSWER} pairs, one at each line, separated by \"$\" symbol.\n\nFor example:\n        an ____ a day, keeps the doctor away$apple\n        sang \"shine bright like a diamond\"$rihanna");
        dataSourcejTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        dataSourcejTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataSourcejTextAreaMouseClicked(evt);
            }
        });
        dataSourcejTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dataSourcejTextAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(dataSourcejTextArea);

        devTeamjTextArea.setEditable(false);
        devTeamjTextArea.setBackground(new java.awt.Color(238, 238, 238));
        devTeamjTextArea.setColumns(20);
        devTeamjTextArea.setLineWrap(true);
        devTeamjTextArea.setRows(5);
        devTeamjTextArea.setText("Built by final year BCompSc students\nFrom Islamabad, Pakistan :)\n\n      Mohammad Raheel  -  [Backend Developer]\n\t<mraheeliftikhar1994@gmail.com>\n\n      Hasaan Ali  - [User Interface Developer]\n\t<hasaan.ali2003@gmail.com>");
        devTeamjTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Developers Team", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        devTeamjTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devTeamjTextAreaMouseClicked(evt);
            }
        });
        devTeamjTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                devTeamjTextAreaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(devTeamjTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlejLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlejLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_formMouseClicked

    private void titlejLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titlejLabelMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_titlejLabelMouseClicked

    private void dataSourcejTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataSourcejTextAreaMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_dataSourcejTextAreaMouseClicked

    private void devTeamjTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devTeamjTextAreaMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_devTeamjTextAreaMouseClicked

    private void titlejLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titlejLabelKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_titlejLabelKeyPressed

    private void dataSourcejTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataSourcejTextAreaKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_dataSourcejTextAreaKeyPressed

    private void devTeamjTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_devTeamjTextAreaKeyPressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_devTeamjTextAreaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dataSourcejTextArea;
    private javax.swing.JTextArea devTeamjTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titlejLabel;
    // End of variables declaration//GEN-END:variables
}
